/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_app_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_servers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Game: {
            title: string;
            imageUrl: string;
            slug: string;
        };
        Traversable: Record<string, never>;
        Games: {
            /**
             * @description An aggregated list of games
             * @default []
             */
            games: components["schemas"]["Game"][];
            iterator: components["schemas"]["Traversable"];
        };
        /** @enum {string} */
        Color: "primary" | "secondary";
        ClassImage: {
            /** @default null */
            color: components["schemas"]["Color"] | null;
            image: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "class";
        };
        Image: {
            image: string;
        } & components["schemas"]["ClassImage"];
        CurseForgeServer: {
            imageUrl: string;
            summary: string;
            downloadCount: number;
            categories: string[];
            author: string;
            date?: string | null;
            version: string;
            additionalData: string;
            title: string;
            slug: string;
            apiLogo: components["schemas"]["Image"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            api: "curseforge";
        };
        Server: {
            title: string;
            imageUrl: string;
            slug: string;
            apiLogo: components["schemas"]["Image"];
        } & components["schemas"]["CurseForgeServer"];
        Servers: {
            /**
             * @description An aggregated list of servers
             * @default []
             */
            servers: components["schemas"]["Server"][];
            iterator: components["schemas"]["Traversable"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_app_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description return dummy data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        path?: string;
                    };
                };
            };
        };
    };
    get_games: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns an object containing the list of games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Games"];
                };
            };
        };
    };
    get_servers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns an object containing the list of the servers of a specifig game by its slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servers"];
                };
            };
        };
    };
}
